export const PRODUCTS = [
  {
    id: "1",
    title: "Jungle Vibes EP",
    artist: "DJ Raggaman",
    label: "Bassline Records",
    price: 22.99,
    category: "jungle",
    image: "https://picsum.photos/300/300?random=1",
    preview: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
  },
  {
    id: "2",
    title: "Liquid Love LP",
    artist: "Smooth Operator",
    label: "DeepGroove",
    price: 25.5,
    category: "liquid",
    image: "https://picsum.photos/300/300?random=2",
    preview: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
  },
  {
    id: "3",
    title: "Roots and Culture",
    artist: "Dubwise",
    label: "Roots Lab",
    price: 19.99,
    category: "dub",
    image: "https://picsum.photos/300/300?random=3",
    preview: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
  },
  {
    id: "4",
    title: "Deep House Chronicles",
    artist: "Mellow Dee",
    label: "Underground Beats",
    price: 27.99,
    category: "house",
    image: "https://picsum.photos/300/300?random=4",
    preview: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
  },
  {
    id: "5",
    title: "Ragga Jungle Riddim",
    artist: "Selector X",
    label: "Jungle City",
    price: 23.5,
    category: "jungle",
    image: "https://picsum.photos/300/300?random=5",
    preview: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
  },
  {
    id: "6",
    title: "Echo Chamber",
    artist: "Dub Scientist",
    label: "Sound System Studio",
    price: 20.0,
    category: "dub",
    image: "https://picsum.photos/300/300?random=6",
    preview: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
  },
  {
    id: "7",
    title: "Sunset Grooves",
    artist: "Chillmasters",
    label: "Oceanic",
    price: 24.0,
    category: "liquid",
    image: "https://picsum.photos/300/300?random=7",
    preview: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
  },
  {
    id: "8",
    title: "Warehouse Rave",
    artist: "909 Unit",
    label: "Raw Trax",
    price: 26.0,
    category: "house",
    image: "https://picsum.photos/300/300?random=8",
    preview: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
  },
  {
    id: "9",
    title: "Heavyweight Dub",
    artist: "Dub Warrior",
    label: "Jah Vibes",
    price: 21.5,
    category: "dub",
    image: "https://picsum.photos/300/300?random=9",
    preview: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
  },
  {
    id: "10",
    title: "Fast Forward",
    artist: "Amen Syndicate",
    label: "Breakbeat Unit",
    price: 22.0,
    category: "jungle",
    image: "https://picsum.photos/300/300?random=10",
    preview: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3",
  },
  {
    id: "11",
    title: "Liquid Dreams",
    artist: "Soul Driver",
    label: "Blue Water",
    price: 25.0,
    category: "liquid",
    image: "https://picsum.photos/300/300?random=11",
    preview: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3",
  },
  {
    id: "12",
    title: "Night Pulse",
    artist: "Low End Theory",
    label: "Minimal House",
    price: 23.0,
    category: "house",
    image: "https://picsum.photos/300/300?random=12",
    preview: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3",
  },
  {
    id: "13",
    title: "Deep Dub FX",
    artist: "Dread Operator",
    label: "Dub Roots",
    price: 18.99,
    category: "dub",
    image: "https://picsum.photos/300/300?random=13",
    preview: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-13.mp3",
  },
  {
    id: "14",
    title: "Atmospheric Jungle",
    artist: "Nebula Bass",
    label: "Dark Wax",
    price: 24.99,
    category: "jungle",
    image: "https://picsum.photos/300/300?random=14",
    preview: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-14.mp3",
  },
  {
    id: "15",
    title: "Floatation Device",
    artist: "Drift Control",
    label: "Liquid Lounge",
    price: 26.5,
    category: "liquid",
    image: "https://picsum.photos/300/300?random=15",
    preview: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-15.mp3",
  },
];
